[supervisord]
nodaemon=true
logfile=/var/log/samba/supervisord.log

[program:samba]
command=/usr/sbin/samba --foreground --no-process-group
autostart=true
autorestart=true
stdout_logfile=/var/log/samba/samba-stdout.log
stderr_logfile=/var/log/samba/samba-stderr.log
