[program:mongodb]
command=/opt/mongodb/bin/mongod --dbpath /data/mongodb --bind_ip 127.0.0.1 --port 27017 --logpath /data/logs/mongodb/mongod.log --quiet
user=conductor
autostart=true
autorestart=true
priority=20
environment=PATH="/opt/mongodb/bin:%(ENV_PATH)s"
stdout_logfile=/data/logs/mongodb/mongod-stdout.log
stderr_logfile=/data/logs/mongodb/mongod-stderr.log
